config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books do
  	resources :genres
  end

  root 'home#index'
  #get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount ReportsKit::Engine, at: '/'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	has_many :books_users
	has_many :users, through: :books_users
	belongs_to :genre

	def to_s
		title
	end
end

app/models/books_user.rb
class BooksUser < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/chart_type.rb
class ChartType < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :books

	def to_s
		name
	end
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books_users
  has_many :books, through: :books_users


  def to_s
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def chart

  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /books
  # GET /books.json
  def index
    if sort_column and sort_direction
      @books = Book.order(sort_column + " " + sort_direction)
    else
      @books = current_user.books
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = current_user.books.build
    #@book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    current_user.books << @book
    #@book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @book = current_user.books.find_by(id: params[:id])
    redirect_to books_path, notice: "Not Authorized To Edit This List" if @book.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :year_of_publishment, :description, :user_id, :edition, :genre_id)
    end

    def sort_column
      Book.column_names.include?(params[:sort]) ? params[:sort] : nil
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : nil
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    @books = Book.paginate(:page => params[:page], per_page: 10)

    # @data = "my_reports"
    # @data = "my_reports2"
    # @data = "my_reports_order_by2"
    # @data = "my_reports_series"

    # Pobierannie parametrów z listy

    # chart_type = ['bar', 'doughnut', 'pie', 'line']
    # kind = params[:kind].presence #|| 0
    #
    # @chart_type = chart_type[kind.to_i]
    # #
    # data = ['my_reports', 'my_reports2', 'my_reports_filters2', 'my_reports_series']
    # rep = params[:rep].presence
    #
    # @data = data[rep.to_i]

    # pobieranie parametrów z tabeli

    @chart_types = ChartType.all
    @reports = Report.all


    # kind = params[:kind].presence ||
    # @chart_type = @chart_types[kind.to_i-1].name

    @chart_type = ChartType.find(params[:kind] || 1)&.name
    # @chart_type = ChartType.find(params[:kind] || 1)&.name


    # rep = params[:rep].presence || 0
    # @report = @reports[rep.to_i].name

    @report = Report.find(params[:rep] || 1)&.name
    @description = Report.find(params[:rep] || 1)&.description

    # if params[:q].present?
    #   @text = "hello #{params[:q]}!"
    # end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  #
  # @chart_types = ChartType.all
  # kind = params[:kind].presence #|| 0
  #
  # @chart_type = @chart_types[kind.to_i].name
  #
  #
  # @reports = Report.all
  # rep = params[:rep].presence
  #
  # @report = @reports[rep.to_i].name
  #

end

app/helpers/books_helper.rb
module BooksHelper

	def sortable(column, title = nil)
	  title ||= column.titleize
	  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
	  link_to title, {:sort => column, :direction => direction}
	end

end

app/helpers/home_helper.rb
module HomeHelper

end

app/views/books/_form.html.erb
<div class='conteiner'>
  <%= form_with(model: book, local: true) do |form| %>
    <% if book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

        <ul>
          <% book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <div class="field">
        <%= form.text_field :title, class:"form-control", placeholder:'Title' %>
      </div>
        <br>
      <div class="field">
        <%= form.text_field :author, class:"form-control", placeholder:'Author' %>
      </div>
        <br>
      <div class="field">
        <%= form.text_area :description, class:"form-control", placeholder:'Book description' %>
      </div>
      <div class="field">
        <%= form.text_field :year_of_publishment, class:"form-control", placeholder:'Year Of Publishment' %>
      </div>

      <div class="field">
        <%= form.label :edition %><br>
        <%= form.select(:edition, options_for_select([['Paper', 'Paper'], ['Ebook', 'Ebook'], ['Audiobook', 'Audiobook']])) %>
      </div>

      <div class="field">
        <%= form.label :genre %><br>
        <%= collection_select(:book, :genre_id, Genre.all, :id, :name, {}, { :multiple => false }) %>
      </div>

        <br>
<!--      <div class="field">-->
        <%#= form.number_field :user_id, id: :book_user_id, class:"form-control", value: current_user.id, type: :hidden %>
<!--      </div>-->
      <div class="field">
        <%#= form.select :user_ids, User::all, class:"form-control" %>
        <%#= form.number_field :users, class:"form-control", value: current_user, type: :hidden %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Read books</h1>

<p>report</p>
<div>
  <%= render_report 'my_reports2' %>
</div>

<br>

<table class="table table-striped table-hover">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Description</th>
      <th>Year Of Publishment</th>
      <th>Genre</th>
      <th>Edition</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <% #if book.users == current_user %>
        <tr>
          <td><strong><%= link_to book.title, book %></strong></td>
          <td><%= book.author %></td>
          <td><%= book.description %></td>
          <td><%= book.year_of_publishment %></td>
          <td><%= book.genre.name %></td>
          <td><%= book.edition %></td>

          <!-- <td><%= link_to 'Show', book %></td> -->
          <td><%= link_to 'Edit', edit_book_path(book), class:"btn btn-outline-dark" %></td>
          <td><%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-dark" %></td>
        </tr>
      <% #end %>
    <% end %>
  </tbody>
</table>

<p><%= sortable "title" %></p>
<p><%= sortable "author" %></p>

<%= link_to 'Add New Book', new_book_path, class:"btn btn-outline-dark" %>

app/views/books/new.html.erb
<h1>New Book</h1><br>

<%= render 'form', book: @book %>

<br>
<%= link_to 'Back', books_path, class: 'btn btn-outline-dark' %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<br>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h4 class="card-title"><strong><%= @book.title %></strong></h4>
    <h5 class="card-subtitle mb-2 text-muted"><%= @book.author %></h5>
    <p class="h6 card-text"><%= @book.description %></p>
    <p class="h6 card-text"><%= @book.year_of_publishment %></p>
    <p class="h6 card-text"><%= @book.edition %></p>
    <p class="h6 card-text"><%= @book.genre.name %></p>
    <a href="#" class="card-link"></a>
  </div>
</div>

<br>

<%= link_to 'Edit', edit_book_path(@book), class:"btn btn-outline-dark" %>
<%= link_to 'Back', books_path, class:"btn btn-outline-dark" %>

app/views/home/_chart.html.erb
<div class="card">
  <div class="card-body">
    <canvas id="myChart" data-chart="<%= @report %>" data-chart_type="<%= @chart_type %>" width="400" height="300"><p>Test chart</p></canvas>
  </div>

  <h4 class="card-title">
    <%= @description %>
  </h4>
</div>

app/views/home/_chart_card.html.erb
<div class="row align-items-start">
  <div class="col">
    <%= render 'home/chart' %>
  </div>
  <div class="col">
    <%= render 'home/select' %>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Home', root_path, class:"navbar-brand" %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Books list", books_path, class:"nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile",  edit_user_registration_path, class:"nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out",  destroy_user_session_path, method: :delete, class:"nav-link active" %>
          </li>
        <% else %>

          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link active" %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/home/_select.html.erb
<div class="conteiner md-3">
	<div class="card mb-3">
		<%= form_tag('/', method: "get") do %>
			<div class="card-title">
				<%= label_tag 'Type of chart' %>
			</div>

		    <div class="card-body">
			    <!--<%#= select_tag(:kind, options_for_select([['Bar chart', 0], ['Doughnut chart', 1], ['Pie chart', 2], ['Line chart', 3]]), selected: :kind, class: "btn btn-outline-dark dropdown-toggle") %>-->

          <%= select_tag(:kind, options_for_select(@chart_types.collect{ |c| [c.name, c.id]}), selected: :kind, class: "btn btn-outline-dark dropdown-toggle") %>

          <%#= select_tag(:rep, options_for_select([['Amount of books per user', 0], ['raport 2', 1], ['raport 3', 2], ['Number of books by genre and date of addition', 3]]), selected: :rep, class: "btn btn-outline-dark dropdown-toggle") %>

          <%= select_tag(:rep, options_for_select(@reports.collect{ |r| [r.description, r.id]}), selected: :rep, class: "btn btn-outline-dark dropdown-toggle") %>

			    <%= submit_tag("Load chart", class: 'btn btn-outline-dark btn-sm') %>
		    </div>
		<% end %>
	</div>

	<!--<div class="card mb-3">-->
		<!--<%= form_tag("/", method: "get") do %>-->
	        <!--<%= text_field_tag(:q, @text, class: 'form-control') %>-->
	        <!--<%= submit_tag("Submit", class: 'btn btn-outline-dark btn-sm') %>-->
		<!--<% end %>	-->
	<!--</div>-->

</div>

app/views/home/index.html.erb
<div class="conteiner">
	<h1 class="mb-4">BOOKSHELF</h1>
	
	<% if user_signed_in? %>
		<h4>Nice to see you! <br><%= link_to "Go to the list", books_path %></h4>
  <% else %>
		<h4 class="mb-3"><%= link_to "Create an account", new_user_registration_path %> to create your own read list</h4>
		
		<h4 class="mb-3">If you already have an account,<br> <%= link_to "sign in", new_user_session_path %> to access your book list</h4>
	<% end %>
</div>

<div>
  <%= render 'home/chart_card' %>
</div>

<h1>All books</h1>

<br>


<table class="table table-striped table-hover table-sm">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Description</th>
      <th>Year Of Publishment</th>
      <th>Genre</th>
      <th>Edition</th>
    </tr>
  </thead>

  <tbody>
    <% @books.all.each do |book| %>
      <tr>
        <td><strong><%= link_to book.title, book %></strong></td>
        <td><%= book.author %></td>
        <td><%= book.description %></td>
        <td><%= book.year_of_publishment %></td>
        <td><%= book.genre.name %></td>
        <td><%= book.edition %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  <%= will_paginate @books, class: 'pagitation-lg m-5' %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Book app</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container>">
    <h1><%= yield %></h1>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

  </body>
</html>